# Generated by Django 6.0.6 on 2026-06-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.CharField(max_length=255)),
                ('absender', models.CharField(max_length=100)),
                ('zeit', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
